#!/bin/sh

# Marker
export MARKER_XPROFILE_="Seeing this means .xprofile is sourced."

# Fcitx5
export INPUT_METHOD=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5

# Java
export _JAVA_AWT_WM_NONREPARENTING=1
