#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
# sh ~/dotfiles/bspsub.sh &
nutstore &
xfsettingsd &
nm-applet &
pa-applet &
sxhkd &
compton &
polybar -r main &
fcitx &
feh --bg-fill --randomize ~/Wallpapers &

# desktop names
bspc monitor -d I II III IV V VI VII VIII IX X

# basic config
bspc config split_ratio             0.5
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true

# appearance
bspc config window_gap              10
bspc config top_padding             25
bspc config border_width            2
bspc config normal_border_color     \#384157
bspc config active_border_color     \#6c99bb
bspc config focused_border_color    \#6c99bb

# monocle
bspc config top_monocle_padding     25
bspc config borderless_monocle      true
;bspc config gapless_monocle         true
