#! /bin/sh

xfsettingsd &
nm-applet &
pa-applet &
sxhkd &
compton &
polybar ery &
fcitx &
feh --bg-fill --randomize ~/Wallpapers &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          7

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     true

bspc config normal_border_color     \#384157
bspc config active_border_color     \#90bee1
bspc config focused_border_color    \#90bee1

bspc rule -a jd manage=off

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
