#!/bin/sh

export VISUAL=vim
export EDITOR=vim

alias ls="ls --color=always"
alias la="ls -A"
alias ll="ls -ahlF"
alias lg="ll | grep"
alias df="df -h"
alias du="du -h -d 1"
alias hg="history | grep"
alias pg="pgrep -f -a"
alias pk="pkill -f"
alias grep="grep -i --color=auto"

alias g="git"
alias v="vim"
alias sv="sudo vim"
alias o="xdg-open"
alias e="emacsclient -n -c"
alias et="emacsclient"
alias hi="history"

alias yaya="yay --aur"
alias yayr="yay --repo"

alias cdot="cd ~/dotfiles"
alias setwp="feh --bg-fill --randomize ~/Wallpapers"

HISTCONTROL=ignoredups:erasedups
HISTSIZE=1000
HISTFILESIZE=1000

function proxy-status() {
    ip=$(curl -sS ifconfig.co)
    echo "current ip is: $ip"

    echo '\n'

    if [ ! -z $proxy_default ] ; then
        echo "proxy_default: $proxy_default"
    else
        echo "proxy_default:"
    fi
    if [ ! -z $proxy ] ; then
        echo "proxy: $proxy"
    else
        echo "proxy:"
    fi

    echo '\n'

    if [ ! -z $http_proxy ] ; then
        echo "http_proxy: $http_proxy"
    else
        echo "http_proxy:"
    fi
    if [ ! -z $https_proxy ] ; then
        echo "https_proxy: $https_proxy"
    else
        echo "https_proxy:"
    fi
}

function proxy-set() {
    export proxy=$1
    proxy-status
}

function proxy-reset() {
    export proxy=$proxy_default
    proxy-status
}

function proxy-on() {
    export {http,https}_proxy=$proxy
    proxy-status
}

function proxy-off() {
    unset {http,https}_proxy
    proxy-status
}

export proxy_default="socks5://127.0.0.1:16666"
export proxy="socks5://127.0.0.1:16666"
