#! /bin/sh

# why do i need this?
systemctl --user import-environment

# start all programs using systemd
systemctl --user start bspwm.target

# setup desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# basic config
bspc config split_ratio             0.5
bspc config focus_follows_pointer   true

# appearance
bspc config window_gap              5
bspc config top_padding             25
bspc config border_width            2
bspc config normal_border_color     \#384157
bspc config active_border_color     \#6c99bb
bspc config focused_border_color    \#6c99bb

# rules
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
