#! /bin/sh

# autostart through systemd
systemctl --user import-environment
systemctl --user start bspwm.target

# basic config
bspc config split_ratio             0.5
bspc config focus_follows_pointer   true

# appearance
bspc config window_gap              5
bspc config top_padding             25
bspc config border_width            2
bspc config normal_border_color     \#384157
bspc config active_border_color     \#6c99bb
bspc config focused_border_color    \#6c99bb

# rules
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
