#! /bin/sh

# autostart
sxhkd &
picom &
nitrogen --restore &
xsetroot -cursor_name left_ptr
# diskie &

# monitor and bar
polybar -r fhd-hdmi-1 & 
polybar -r fhd-dvi-d-1 &
bspc monitor HDMI-0 -d I II III IV V 
bspc monitor DVI-D-0 -d VI VII VIII IX X

# basic config
bspc config split_ratio             0.5
bspc config focus_follows_pointer   true

# appearance
bspc config window_gap              5
bspc config top_padding             25
bspc config border_width            2
bspc config normal_border_color     \#384157
bspc config active_border_color     \#6c99bb
bspc config focused_border_color    \#6c99bb

# rules
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
